name: Copy GitHub Environment Variables
description: "Copy variables from one GitHub environment to another using GitHub CLI"

inputs:
  SOURCE_ENVIRONMENT:
    description: "The name of the source GitHub environment to copy variables from."
    required: true
  DESTINATION_ENVIRONMENT:
    description: "The name of the destination GitHub environment to copy variables to."
    required: true
  VARIABLES:
    description: "A comma-separated list of specific existing variable names to copy. If not provided, all variables will be copied."
    required: false
    default: "[]"

runs:
  using: "composite"
  steps:
  - name: Copy existing GitHub Environment Variables
    shell: bash
    env:
      GH_TOKEN: ${{ env.GHTOKEN }}
    run: |
        set -euo pipefail

        SRC_ENV="${{ inputs.SOURCE_ENVIRONMENT }}"
        DEST_ENV="${{ inputs.DESTINATION_ENVIRONMENT }}"
        VARS_TO_COPY="${{ inputs.VARIABLES }}"

        response="$(gh api repos/${{ github.repository }}/environments/$SRC_ENV/variables)"

        if [[ "$(jq -r '(.variables // []) | length' <<< "$response")" -eq 0 ]]; then
          echo "⚠️ No variables found for environment: $SRC_ENV. Nothing to copy."
          exit 0
        fi

        jq -c '(.variables // [])[]' <<< "$response" | while read -r var; do
          if [[ "$VARS_TO_COPY" == "[]" || -z "$VARS_TO_COPY" ]]; then
            name=$(echo "$var" | jq -r '.name')
          else
            echo "$VARS_TO_COPY" | jq -r '.[]' | while read -r var_name; do
              name="$var_name"
            done
          fi

          value=$(echo "$var" | jq -r '.value')
            if gh api repos/${{ github.repository }}/environments/$SRC_ENV/variables/$name >/dev/null 2>&1; then
              if gh api repos/${{ github.repository }}/environments/$DEST_ENV/variables/$name >/dev/null 2>&1; then
                echo "⚠️ '$name' variable already exists. Skipping copy of '$name'."
              else
                echo "ℹ️ Copying variable '$name' from environment '$SRC_ENV' to environment '$DEST_ENV'."
                gh api --method POST -H 'Accept: application/vnd.github+json' "repos/${{ github.repository }}/environments/$DEST_ENV/variables" -f name="$name" -f value="$value"
              fi
            else
              echo "⚠️ '$name' variable does not exist in environment '$SRC_ENV'. Skipping."
            fi
        done

        echo "✅ Repository environment variables copy process completed."
