name: GitHub APP Auth
description: "Autentica com o GitHub App para obter um token de acesso"

runs:      
  using: "composite"
  steps:
    - name: Anunciar Autenticação com GitHub App
      run: |
        echo "🔑 ===== [AUTH GITHUB APP] Iniciando autenticação com o GitHub App para obter um token de acesso. ====="
      shell: bash

    - name: Autenticar com GitHub App
      uses: actions/create-github-app-token@v2.2.1
      id: generate-token
      with:
          app-id: ${{ env.WF_APP_ID }}
          private-key: ${{ env.WF_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

    - name: Exportar Token Gerado
      run: |
        echo "::notice title=TOKEN GERADO::Token de acesso do GitHub App foi gerado com sucesso e será exportado."
        # Exporta o token para a variável de ambiente GHTOKEN
        echo "GHTOKEN=${{ steps.generate-token.outputs.token }}" >> $GITHUB_ENV
        echo "✅ ===== [AUTH GITHUB APP] Token exportado para a variável de ambiente GHTOKEN. ====="
      shell: bash
