name: Gerar output de jobs matriz
description: Gerar output de jobs matriz para exportar variáveis de ambiente dos ambientes temporários criados para importação de variáveis (prd-temp, tqs-temp)

runs:
  using: "composite"
  steps:
    - name: Gerar output de jobs matriz
      run: |
      echo "{\"env-temp\":\"${{ matrix.AMBIENTE }}-temp\"}" > output-env-temp.json
    
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: output-${{ matrix.AMBIENTE }}
        path: output-env-temp.json