name: Environment Variables File (Arquivo de variáveis globais)
description: "Exporta variáveis globais de git files para qualquer Service/API/MFE/RN/Lib .NET/JS"

outputs:
  VARS_FILE:
    description: "Variáveis globais de git files para Services API .NET"
    value: ${{ steps.set-vars-file.outputs.VARS_FILE }}

runs:
  using: "composite"
  steps:
    - name: Install envsubst
      run: sudo apt-get update && sudo apt-get install -y gettext-base
      shell: bash

    - name: Checkout Global Vars Files
      uses: actions/checkout@v5
      with:
        repository: Illusion-Factory-Labs/${{ env.GLOBAL_REPO_VAR }}
        ref: main
        path: ${{ env.GLOBAL_REPO_VAR }}
        token: ${{ env.GH_PAT }}
        clean: true

    - name: Set project variables file by project type/group
      run: |
        infra_vars_file="vg_api_infra_global.json"
        service_vars_file="vg_api_service_global.json"
        
        for varsfile in "$infra_vars_file" "$service_vars_file"; do
          if [ ! -f ./$GLOBAL_REPO_VAR/${AMBIENTE}/$varsfile ]; then
            echo "Arquivo não encontrado: ./$GLOBAL_REPO_VAR/${AMBIENTE}/$varsfile" >&2
            exit 1
          fi
        done

        vars_file=$(jq -s -c 'add' \
          ./$GLOBAL_REPO_VAR/${AMBIENTE}/$infra_vars_file \
          ./$GLOBAL_REPO_VAR/${AMBIENTE}/$service_vars_file \
          | envsubst)
        echo "$vars_file"
        echo "VARS_FILE=$vars_file" >> $GITHUB_OUTPUT
        echo "::notice title=📝 VARIÁVEIS EXPORTADAS::Arquivo de variáveis globais exportado com sucesso para $AMBIENTE."
      id: set-vars-file

      shell: bash