name: Variables
description: Import variables
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run:
        gh variable set API_URL \
          --env prd \
          --body "https://api.prod.example.com"
      shell: bash