name: Copy GitHub Environment Variables
description: "Copy variables from one GitHub environment to another using GitHub CLI"

inputs:
  SOURCE_ENVIRONMENT:
    description: "The name of the source GitHub environment to copy variables from."
    required: true
  DESTINATION_ENVIRONMENT:
    description: "The name of the destination GitHub environment to copy variables to."
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy GitHub Environment Variables
      shell: bash
      env:
        GH_TOKEN: ${{ env.GHTOKEN }}
      run: |
        # Check if source environment exists
        if ! gh api repos/${{ github.repository }}/environments --jq '.environments[].name' | grep -Fxq -- "${{ inputs.SOURCE_ENVIRONMENT }}"; then
          echo "Source environment '${{ inputs.SOURCE_ENVIRONMENT }}' does not exist."
          exit 1
        fi

        # Check if destination environment exists, if not create it
        if ! gh api repos/${{ github.repository }}/environments --jq '.environments[].name' | grep -Fxq -- "${{ inputs.DESTINATION_ENVIRONMENT }}"; then
          echo "Destination environment '${{ inputs.DESTINATION_ENVIRONMENT }}' does not exist. Creating it..."
          gh api repos/${{ github.repository }}/environments -f name="${{ inputs.DESTINATION_ENVIRONMENT }}"
        fi

        # Get variables from source environment and copy to destination environment
        variables=$(gh variable list --repo ${{ github.repository }} --env ${{ inputs.SOURCE_ENVIRONMENT }} --visibility all --json name,value)
        echo "$variables" | jq -c '.[]' | while read variable; do
          name=$(echo "$variable" | jq -r '.name')
          value=$(echo "$variable" | jq -r '.value')
          echo "Copying variable '$name' to environment '${{ inputs.DESTINATION_ENVIRONMENT }}'"
          gh variable set "$name" --repo ${{ github.repository }} --env ${{ inputs.DESTINATION_ENVIRONMENT }} --body "$value"
        done