name: Copy GitHub Environment Variables
description: "Copy variables from one GitHub environment to another using GitHub CLI"

inputs:
  SOURCE_ENVIRONMENT:
    description: "The name of the source GitHub environment to copy variables from."
    required: true
  DESTINATION_ENVIRONMENT:
    description: "The name of the destination GitHub environment to copy variables to."
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy GitHub Environment Variables
      shell: bash
      env:
        GH_TOKEN: ${{ env.GHTOKEN }}
      run: |
        set -euo pipefail


        if [[ "${{ inputs.SOURCE_ENVIRONMENT }}" != "prd" && "${{ inputs.SOURCE_ENVIRONMENT }}" != "tqs" ]]; then
            echo "::notice::No need to run script for environment: ${{ inputs.SOURCE_ENVIRONMENT }}. Script will only run if values are 'prd' or 'tqs'."
          exit 0
        fi

        response="$(gh api repos/${{ github.repository }}/environments/${{ inputs.SOURCE_ENVIRONMENT }}/variables)"

        if [[ "$(jq -r '(.variables // []) | length' <<< "$response")" -eq 0 ]]; then
          echo "::notice::No variables found for environment: ${{ inputs.SOURCE_ENVIRONMENT }}"
          exit 0
        fi

        jq -c '(.variables // [])[]' <<< "$response" | while read -r var; do
            name=$(echo "$var" | jq -r '.name')
            value=$(echo "$var" | jq -r '.value')
            

            if gh api repos/${{ github.repository }}/environments/${{ inputs.DESTINATION_ENVIRONMENT }}/variables/$name >/dev/null 2>&1; then
                echo "::warning::'$name' variable already exists. Skipping copy of '$name'."
            else
                echo "::notice::Copying variable '$name' from environment '${{ inputs.SOURCE_ENVIRONMENT }}' to environment '${{ inputs.DESTINATION_ENVIRONMENT }}'."
                gh api --method POST -H 'Accept: application/vnd.github+json' "repos/${{ github.repository }}/environments/${{ inputs.DESTINATION_ENVIRONMENT }}/variables" -f name="$name" -f value="$value"
            fi
        done

        echo "::notice::Repository environment variables copy process completed."
