name: Api Dotnet

on:
  push:
    branches: [main]


jobs:  
    build:
        runs-on: ubuntu-latest
        outputs:
          changed_vars_json_array: ${{ steps.set_changed_vars.outputs.changed_vars_json_array }}
          chnged_vars_json_map: ${{ steps.set_changed_vars.outputs.changed_vars_json_map }}
        steps:
        - run: |
            changed_vars_json_array='["VAR_A", "VAR_B"]'
            declare -A changed_vars_json_map=(
              ["VAR_A"]="value_a"
              ["VAR_B"]="value_b"
            )
            echo $changed_vars_json_array
            echo $changed_vars_json_map

            echo "changed_vars_json_array=$changed_vars_json_array" >> $GITHUB_OUTPUT
            echo "chnged_vars_json_map=$(declare -p changed_vars_json_map)" >> $GITHUB_OUTPUT
        
    log:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - run: |
            echo "Changed Vars JSON Array: ${{ needs.build.outputs.changed_vars_json_array }}"
            echo "Changed Vars JSON Map: ${{ needs.build.outputs.chnged_vars_json_map }}"


