name: Workflow 01

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  GLOBAL_REPO_VAR: github-repo-variables
  GH_PAT: ${{ secrets.GH_PAT }}
  WF_APP_ID: ${{ secrets.WF_APP_ID }}
  WF_APP_PRIVATE_KEY: ${{ secrets.WF_APP_PRIVATE_KEY }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

defaults:
  run:
    shell: bash

jobs:
  test-variables:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     AMBIENTE: [prd, des, tqs, qa]
    # environment: ${{ matrix.AMBIENTE == 'prd' && 'prd-vars' || matrix.AMBIENTE == 'tqs' && 'tqs-vars' || matrix.AMBIENTE }}
    # steps:
    #   - name: "File Variable Groups '${{ matrix.AMBIENTE }}'"
    #     id: file-variable-group
    #     uses: Illusion-Factory-Labs/github-repo-templates/actions/components/file-variable-group@main
    #     with:
    #       AMBIENTE: ${{ matrix.AMBIENTE }}
      
      