name: Workflow 01

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  SERVER: Production

defaults:
  run:
    shell: bash

jobs:
  test-variables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        AMBIENTE: [prd, des, des-vars]
    environment:
      name: ${{ matrix.AMBIENTE }}
    steps:
      - name: Print Environment Variable
        run: |
          echo "The current environment is: ${{ matrix.AMBIENTE }}"
          echo "The environment variables are: "
          echo "${{ vars }}"